### ISSUE TITLE
tried  a docker installation without success

### ISSUE THREAD

**Issue by bfilippi** [quantlabio/quantlab#1]
Hi 
I have been curious on seeing what you are working on. 

Unfortunately I couldn't install your package 

I run the following
docker run -i -t -p 8888:8888 continuumio/anaconda /bin/bash

root@2431933489ae:/#  conda install -c conda-forge quantlab
Fetching package metadata ...........

PackageNotFoundError: Package missing in current linux-64 channels: 
  - quantlab

Close matches found; did you mean one of these?

    quantlab: quandl

#so I tried the pip way
root@2431933489ae:/# pip install quantlab
Collecting quantlab
  Downloading quantlab-0.1.1-py2.py3-none-any.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 218kB/s 
Requirement already satisfied: notebook>=4.3.1 in /opt/conda/lib/python2.7/site-packages (from quantlab)
Collecting quantlab-launcher>=0.1.0 (from quantlab)
  Downloading quantlab_launcher-0.1.1-py2.py3-none-any.whl
Installing collected packages: quantlab-launcher, quantlab
Successfully installed quantlab-0.1.1 quantlab-launcher-0.1.1

root@2431933489ae:/# jupyter serverextension enable --py quantlab --sys-prefix
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-serverextension", line 6, in <module>
    sys.exit(notebook.serverextensions.main())
  File "/opt/conda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python2.7/site-packages/notebook/serverextensions.py", line 293, in start
    super(ServerExtensionApp, self).start()
  File "/opt/conda/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/opt/conda/lib/python2.7/site-packages/notebook/serverextensions.py", line 210, in start
    self.toggle_server_extension_python(arg)
  File "/opt/conda/lib/python2.7/site-packages/notebook/serverextensions.py", line 199, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/opt/conda/lib/python2.7/site-packages/notebook/serverextensions.py", line 327, in _get_server_extension_metadata
    m = import_item(module)
  File "/opt/conda/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/opt/conda/lib/python2.7/site-packages/quantlab/__init__.py", line 7, in <module>
    from .extension import load_jupyter_server_extension
  File "/opt/conda/lib/python2.7/site-packages/quantlab/extension.py", line 8, in <module>
    from quantlab_launcher import add_handlers, LabConfig
**ImportError: cannot import name LabConfig**

**Comment by lab4quant** [comment]
@bfilippi , apologies for the confusion, the documents were forked from jupyterlab, we just started this project, the conda-forge install is not ready yet, we're working on the feedstock creation. 

for pip install, there's discrepancy between quantlab_launcher and quantlab, I submitted a new package today, which should fix the pip install part

right now, it's exactly same as jupyterlab, our ideas are not implemented yet

**Comment by lab4quant** [comment]
@bfilippi , the conda install is fixed, there isn't much new yet, we're trying to add calendar and spread sheet, it's still in very early stage, we added 2 sample files in example folder, they can be opened by calendar / sheet
